//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edition {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControl() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edition.ResourceControl", typeof(ResourceControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function intAccordion() { var userpanel = $(&quot;##acc#&quot;); var index = $.cookie(&quot;##acc#&quot;); var active = 0; if (index !== undefined) { active = userpanel.find(&quot;h2:eq(&quot; + index + &quot;)&quot;); } if (index == null) active = 0;$(&quot;##acc#&quot;).accordion({ header: &quot;h2&quot;, autoHeight: false, active: active, change: function (event, ui) { var i = $(this).find(&quot;h2&quot;).index(ui.newHeader[0]); $.cookie(&quot;##acc#&quot;, i, { path: &quot;/&quot; }); } });});.
        /// </summary>
        internal static string accordionCore {
            get {
                return ResourceManager.GetString("accordionCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///
        ///
        ///function submitValidateRegExp(obj, regs) {
        ///
        ///    if (!new RegExp(regs, &apos;g&apos;).test($(obj).val())) {
        ///        $(obj).css(&apos;background-color&apos;, &apos;#FF0000&apos;);
        ///        return 1;
        ///    }
        ///    else {
        ///        return 0;
        ///    }
        ///}
        ///function submitValidateIsEmpty(obj, isNull, strlength) {
        ///    var str = $(obj).val();
        ///    if (strlength &lt;= 0)
        ///        strlength = 4000000000000000;
        ///    if (str.length &gt; strlength) {
        ///        alert(&apos;Big amount symbol!&apos;);
        ///        $(obj).css(&apos;background-color&apos;, &apos;#FF0000&apos;);
        ///        r [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  /*Code Compressed with JS Code Compressor v.1.0.3 - http://www.sarmal.com/*/function submitValidateRegExp(obj,regs){if (!new RegExp(regs,&apos;g&apos;).test($(obj).val())){$(obj).css(&apos;background-color&apos;,&apos;#FF0000&apos;);return 1;}else{return 0;}}function submitValidateIsEmpty(obj,isNull,strlength){var str = $(obj).val();if (strlength &lt;= 0)strlength = 4000000000000000;if (str.length &gt; strlength){alert(&apos;Big amount symbol!&apos;);$(obj).css(&apos;background-color&apos;,&apos;#FF0000&apos;);return 1;}if (isNull){if ($.trim(str).length == 0){$(obj).css [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Base_compressed {
            get {
                return ResourceManager.GetString("Base_compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function () {$(&quot;input:file&quot;).parents().each(function () { if ($(this).is($(&apos;form&apos;))) {$(this).attr(&apos;enctype&apos;, &apos;multipart/form-data&apos;);}});});.
        /// </summary>
        internal static string cb {
            get {
                return ResourceManager.GetString("cb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;table style=&quot;width: 100px&quot;  &gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///   &lt;label class=&quot;editionlabel&quot;&gt; #titl#&lt;br/&gt;
        ///        &lt;input id=&quot;#12#&quot; name=&quot;#12#&quot; type=&quot;text&quot; #json#  #hh# value=&quot;#date#&quot; /&gt;&lt;/label&gt; &lt;/td&gt;
        ///    &lt;td style=&quot;vertical-align: bottom&quot; &gt;
        ///        &lt;input id=&quot;#12#_bt&quot; class=&quot;buttonModalTinyMce&quot; type=&quot;button&quot;  value=&quot;...&quot; onclick=&quot;showDatepicker(&apos;#12#&apos;,&apos;#13#&apos;);return false;&quot; /&gt;&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td colspan=&quot;2&quot;&gt;
        ///        &lt;div id=&quot;#12#_div&quot; class=&quot;modalDatePitcker&quot; &gt;
        ///        &lt;table style=&quot;width: 100px&quot; &gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string datePicker {
            get {
                return ResourceManager.GetString("datePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///$($(function () {
        ///    var obj = $.parseJSON(&apos;#str#&apos;);
        ///    $.each(obj, function (i, val) {
        ///
        ///
        ///
        ///        if ($(&apos;#&apos; + i + &apos;&apos;).is(&apos;input&apos;) || $(&apos;#&apos; + i + &apos;&apos;).is(&apos;select&apos;) || $(&apos;#&apos; + i + &apos;&apos;).is(&apos;textarea&apos;)) {
        ///
        ///            if ($(&apos;#&apos; + i + &apos;&apos;).is(&apos;[type =checkbox]&apos;) &amp;&amp; val == true) {
        ///                $(&apos;#&apos; + i + &apos;&apos;).attr(&apos;checked&apos;, &apos;checked&apos;);
        ///            $(&apos;[type =hidden]&amp;&amp;[id = &apos; + i + &apos;]&apos;).remove();
        ///
        ///        }
        ///        $(&apos;#&apos; + i + &apos;&apos;).val(val);
        ///    }
        ///    else {
        ///            alert(i);
        ///            $ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string loader {
            get {
                return ResourceManager.GetString("loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    &lt;div id=&quot;maska&quot; style=&quot;  display:none;    top: 0px; left: 0px;     z-index: 999;  background-color: #C0C0C0;  position: fixed;&quot;&gt;&lt;/div&gt;
        ///       
        ///      
        ///      
        ///     
        ///      
        ///         
        ///         
        ///          
        ///    
        ///.
        /// </summary>
        internal static string maska {
            get {
                return ResourceManager.GetString("maska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function(){$dialog = $(&apos;#editionmodal&apos;).dialog({autoOpen: false, title: &apos;#titl#&apos;, dialogClass: &apos;alert&apos;, modal: true,buttons: [{ text: &quot;#n#&quot;, click: function () { $(this).dialog(&quot;close&quot;); } }, { text: &quot;#y#&quot;, click: function () { $(this).dialog(&quot;close&quot;);#code# $(&quot;##form#&quot;).submit(); } }]});$(&apos;##button#&apos;).bind(&apos;click&apos;, function () {$dialog.dialog(&quot;open&quot;);  return false;});});.
        /// </summary>
        internal static string modalDialog {
            get {
                return ResourceManager.GetString("modalDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function() {
        ///    // $(&apos;form&apos;).submit( validateCore());
        ///});.
        /// </summary>
        internal static string submitValidate {
            get {
                return ResourceManager.GetString("submitValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function () {
        ///    $(&quot;##acc#&quot;).tabs(
        ///        { 
        ///            cookie: { expires: 5 }, autoHeight: false, active: 0
        ///        });
        ///});
        ///.
        /// </summary>
        internal static string tabsCore {
            get {
                return ResourceManager.GetString("tabsCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///
        ///        function tynyUp(tb){
        ///
        ///       try{
        ///         tinyMCE_GZ.init({
        ///        plugins : &apos;autolink,lists,pagebreak,style,layer,table,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,filion&apos;,
        ///        themes : &apos;simple,advanced&apos;,
        ///        languages : &apos;ru&apos;,
        ///        disk_cache : true,
        ///        debug : false
        ///});
        ///
        ///        tinyMCE.ini [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tinyMCE {
            get {
                return ResourceManager.GetString("tinyMCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $(function load#name#(){tynyUp(&apos;#name#&apos;);});.
        /// </summary>
        internal static string updateModel {
            get {
                return ResourceManager.GetString("updateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  function validateCore() {
        ///
        /// if( $(&apos;#IsValidate&apos;).length ){
        ///   if($(&apos;#IsValidate&apos;).val()==&apos;False&apos;) return true;
        /// }
        /// var error1=0; var error2=0;  #validate# if(error1 &gt; 0||error2 &gt; 0)
        ///  {
        ///   alert(&apos;Error input..&apos;);if(error1 &gt; 0) {$(&apos;#error_1&apos;).css(&apos;display&apos;,&apos;block&apos;);   }if(error2&gt;0) {  $(&apos;#error_2&apos;).css(&apos;display&apos;,&apos;block&apos;); }return false;} $(&apos;#error_1&apos;).css(&apos;display&apos;,&apos;none&apos;); $(&apos;#error_2&apos;).css(&apos;display&apos;,&apos;none&apos;);  return true; }.
        /// </summary>
        internal static string valudateCore {
            get {
                return ResourceManager.GetString("valudateCore", resourceCulture);
            }
        }
    }
}
